Models/Alumnos.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lab1.Models
{
    public class Alumnos
    {
        public String nombre { get; set; }
        public String  Curso { get; set; }
        public int  credito { get; set; }
        public double Result { get; set; }
    }

}

Models/ErrorViewModel.cs
namespace Lab1.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/AlumnosController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Lab1.Models;
using Microsoft.Extensions.Logging;


namespace Lab1.Controllers
{
    public class AlumnosController : Controller
    {

        private readonly ILogger<AlumnosController> _logger;
        public AlumnosController(ILogger<AlumnosController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

     

        [HttpPost]
		public IActionResult Alumno(
             Alumnos alumno)
		{

            int pago =0;
            alumno.credito=300;
            int canCreditos=0;
			double valigv=0;
           

             if("HISTORIA".Equals(alumno.Curso)){
                pago=alumno.credito+pago;
                canCreditos+=3;
            }
            if("MATEMATICA".Equals(alumno.Curso)){
                pago=alumno.credito+pago;
                canCreditos+=3;
            }
            if("LENGUAJE".Equals(alumno.Curso)){
                pago=alumno.credito+pago;
                canCreditos+=3;
            }
            
            
            
            valigv=pago*1.18-pago;
            alumno.Result=pago+valigv;

            
            ViewData["Message"] = "Resultado: NOMBRE DEL ALUMNO:  "+alumno.nombre+"\n TOTAL DE CURSOS INSCRITOS:  "+canCreditos+"\n PAGO POR CURSOS:  "+pago+"\n IGV:  "+valigv+"\n TOTAL A PAGAR:  "+alumno.Result ;
            return View("Index",alumno);
		}


        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Lab1.Models;

namespace Lab1.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Alumnos/index.cshtml
@model Lab1.Models.Alumnos
@{
    ViewData["Title"] = "Calculadora";
}
<h2>@ViewData["Title"]</h2>
<div class="row">
<div class="col-md-4">
<form asp-action="Alumno" asp-controller="Alumnos" >
    
     <div class="form-group">
        <label asp-for="nombre"> Nombre Alumno </label>
        <input asp-for="nombre" class="form-control" />
    </div>
       
       <label asp-for="Curso"> Curso a elegir: </label>
        
       <div class="form-check mb-3">

                            <input class="form-check-input" asp-type="checkbox" name="HISTORIA"asp-for="Curso" value="HISTORIA" id="flexCheckDefault"/>
                                    HISTORIA
                        
        </div>

        <div class="form-check mb-3">
                <label asp-for="Curso" class="form-label">
                            <input class="form-check-input" asp-type="checkbox" name="MATEMATICA" asp-for="Curso" value="MATEMATICA" id="flexCheckDefault"/>
                                    MATEMATICA
                        </label>
        </div>
        <div class="form-check mb-3">
                <label asp-for="Curso" class="form-label">
                            <input class="form-check-input"  asp-type="checkbox" asp-for="Curso" value="LENGUAJE" id="flexCheckDefault"/>
                                    LENGUAJE
                        </label>
        </div>


    <div class="form-group">
        <input type="submit" value="Alumno" class="btn btn-primary" />
    </div>
</form>
</div>
</div>
<h3>@ViewData["Message"]</h3>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lab1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lab1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Alumnos" asp-action="Index">Formulario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Lab1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>